{
 "title": "400G ZR",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Router_A",
    "label": "Router A",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(bucket: \"telegraf\", measurement: \"Cisco-IOS-XR-controller-otu-oper:otu/controllers/controller/info\", tag: \"source\")"
   },
   {
    "name": "Router_A_Port",
    "label": "Router A Port",
    "query": "SHOW TAG VALUES FROM \"Cisco-IOS-XR-controller-otu-oper:otu/controllers/controller/info\" WITH KEY=\"controller_name\"  WHERE source =~ /$Router_A/ "
   },
   {
    "name": "Router_B",
    "label": "Router_B",
    "query": "from(bucket: \"telegraf\")\n  |> range(start: 0, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openconfig-lldp:lldp/interfaces/interface/neighbors/neighbor\")\n  |> filter(fn: (r) => r[\"name\"] == \"${router_a_interface_id}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state/system_name\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_A}\")"
   },
   {
    "name": "Router_B_Port",
    "query": "\n  from(bucket: \"telegraf\")\n  |> range(start: 0, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openconfig-lldp:lldp/interfaces/interface/neighbors/neighbor\")\n  |> filter(fn: (r) => r[\"name\"] == \"${router_a_interface_id}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state/port_id\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_A}\")"
   },
   {
    "name": "Router_B_Port_BAK",
    "label": "Router_B_Port_BAK",
    "query": "from(bucket: \"telegraf\")\n  |> range(start: 0, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"topology-1\")\n  |> filter(fn: (r) => r[\"Source\"] == \"${Router_A}\")\n  |> filter(fn: (r) => r[\"Source_Port\"] == \"${Router_A_Port}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Dest_Port\")"
   },
   { "name": "pm_time_range", "label": "PM Time Range", "query": "second30,minute15,hour24" },
   {
    "name": "otu_pm_path",
    "query": "import \"influxdata/influxdb/schema\"\nschema.measurements(bucket: \"telegraf\")"
   },
   {
    "name": "router_a_interface_id",
    "label": "Router A Interface ID",
    "query": "SHOW TAG VALUES FROM \"openconfig-lldp:lldp/interfaces/interface/neighbors/neighbor\" WITH KEY=\"name\"  WHERE source =~ /$Router_A/"
   },
   {
    "name": "router_b_interface_id",
    "query": "\n  from(bucket: \"telegraf\")\n  |> range(start: 0, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openconfig-lldp:lldp/interfaces/interface/neighbors/neighbor\")\n  |> filter(fn: (r) => r[\"name\"] == \"${router_a_interface_id}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state/port_id\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_A}\")"
   }
  ]
 },
 "panels": [
  { "title": "$Router_A $Router_A_Port", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transport Admin State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT \"transport_admin_state\" FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" =~ /^$Router_A$/ AND \"name\" = 'Optics$Router_A_Port' ) AND $timeFilter"
    }
   ]
  },
  {
   "title": "LED",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info",
     "query": "SELECT \"led_state\" FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" =~ /^$Router_A$/ AND \"name\" = 'Optics$Router_A_Port' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "led_state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Router_A$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Router_A_Port$/" }
     ]
    }
   ]
  },
  {
   "title": "Optic Controller",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT \"controller_state\" FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" =~ /^$Router_A$/ AND \"name\" = 'Optics$Router_A_Port' ) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Laser",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info",
     "query": "SELECT \"laser_state\" FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" =~ /^$Router_A$/ AND \"name\" = 'Optics$Router_A_Port' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "led_state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Router_A$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Router_A_Port$/" }
     ]
    }
   ]
  },
  {
   "title": "Optics Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info",
     "query": "SELECT \"derived_optics_type\" FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" =~ /^$Router_A$/ AND \"name\" = 'Optics$Router_A_Port') AND $timeFilter",
     "select": [
      [
       { "params": [ "modulation_type" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Router_A$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Optics0/0/0/29" }
     ]
    }
   ]
  },
  {
   "title": "Modulation Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info",
     "query": "SELECT \"modulation_type\" FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" =~ /^$Router_A$/ AND \"name\" = 'Optics$Router_A_Port') AND $timeFilter",
     "select": [
      [
       { "params": [ "modulation_type" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Router_A$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Optics0/0/0/29" }
     ]
    }
   ]
  },
  {
   "title": "Frequency ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "THz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"dwdm_carrier_frequency\")\n  |> filter(fn: (r) => r[\"name\"] == \"Optics\"+\"${Router_A_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_A}\")\n  "
    }
   ]
  },
  {
   "title": "wavelength ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "nm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"dwdm_carrier_wavelength\")\n  |> filter(fn: (r) => r[\"name\"] == \"Optics\"+\"${Router_A_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_A}\")\n  "
    }
   ]
  },
  {
   "title": "Pre-FEC/Post-FEC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-controller-otu-oper:otu/controllers/controller/info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"otu_fec_satistics/pre_fec_ber\")\n  |> filter(fn: (r) => r[\"controller_name\"] == \"CoherentDSP\"+\"${Router_A_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_A}\")\n  |> map(fn: (r) => ({r with _value: float(v: r._value)}))\n  "
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-controller-otu-oper:otu/controllers/controller/info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"otu_fec_satistics/post_fec_ber\")\n  |> filter(fn: (r) => r[\"controller_name\"] == \"CoherentDSP\"+\"${Router_A_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_A}\")\n  |> map(fn: (r) => ({r with _value: float(v: r._value)}))\n  "
    }
   ]
  },
  {
   "title": "RX/TX dBm",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-lanes/optics-lane\")\n  |> filter(fn: (r) => r[\"_field\"] == \"receive_power\")\n  |> filter(fn: (r) => r[\"name\"] == \"Optics\"+\"${Router_A_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_A}\")\n  |> map(fn: (r) => ({r with _value: r._value / 100}))\n  "
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-lanes/optics-lane\")\n  |> filter(fn: (r) => r[\"_field\"] == \"transmit_power\")\n  |> filter(fn: (r) => r[\"name\"] == \"Optics\"+\"${Router_A_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_A}\")\n  |> map(fn: (r) => ({r with _value: r._value / 100}))\n  \n  "
    }
   ]
  },
  {
   "title": "Qmargin/Qfactor dB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${otu_pm_path}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"q/average\")\n  |> filter(fn: (r) => r[\"name\"] == \"CoherentDSP\"+\"${Router_A_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_A}\")\n  |> map(fn:(r) => ({ r with _value: float(v: r._value) }))\n  "
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${otu_pm_path}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"qmargin/average\")\n  |> filter(fn: (r) => r[\"name\"] == \"CoherentDSP\"+\"${Router_A_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_A}\")\n  |> map(fn:(r) => ({ r with _value: float(v: r._value) }))\n  "
    }
   ]
  },
  {
   "title": "EC/UC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-pmengine-oper:performance-management/otu/otu-ports/otu-port/otu-current/otu-second30/otu-second30fecs/otu-second30fec",
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${otu_pm_path}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ec_bits/data\" or r[\"_field\"] == \"uc_words/data\")\n  |> filter(fn: (r) => r[\"name\"] == \"CoherentDSP\"+\"${Router_A_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_A}\")",
     "select": [
      [
       { "params": [ "ec_bits/data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Router_A$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "CoherentDSP0/0/0/29" }
     ]
    }
   ]
  },
  {
   "title": "OSNR/ESNR dB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"optical_signal_to_noise_ratio\" or r[\"_field\"] == \"snr\" )\n  |> filter(fn: (r) => r[\"name\"] == \"Optics\"+\"${Router_A_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_A}\")\n  |> map(fn:(r) => ({ r with _value: float(v: r._value) }))\n  "
    }
   ]
  },
  {
   "title": "Temperature ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lane_data/laser_temperature\")\n  |> filter(fn: (r) => r[\"name\"] == \"Optics\"+\"${Router_A_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_A}\")\n  |> map(fn: (r) => ({r with _value: r._value / 100}))\n  "
    }
   ]
  },
  { "title": "$Router_B $Router_B_Port", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Transport Admin State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT \"transport_admin_state\" FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" =~ /^$Router_B$/ AND \"name\" = 'Optics$Router_B_Port' ) AND $timeFilter"
    }
   ]
  },
  {
   "title": "LED",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info",
     "query": "SELECT \"led_state\" FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" =~ /^$Router_B$/ AND \"name\" = 'Optics$Router_B_Port' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "led_state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Router_A$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Router_A_Port$/" }
     ]
    }
   ]
  },
  {
   "title": "Optic Controller",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT \"controller_state\" FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" =~ /^$Router_B$/ AND \"name\" = 'Optics$Router_B_Port' ) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Laser",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info",
     "query": "SELECT \"laser_state\" FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" =~ /^$Router_B$/ AND \"name\" = 'Optics$Router_B_Port' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "led_state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Router_A$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Router_A_Port$/" }
     ]
    }
   ]
  },
  {
   "title": "Optics Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info",
     "query": "SELECT \"derived_optics_type\" FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" =~ /^$Router_B$/ AND \"name\" = 'Optics$Router_B_Port') AND $timeFilter",
     "select": [
      [
       { "params": [ "modulation_type" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Router_A$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Optics0/0/0/29" }
     ]
    }
   ]
  },
  {
   "title": "Modulation Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info",
     "query": "SELECT \"modulation_type\" FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" =~ /^$Router_B$/ AND \"name\" = 'Optics$Router_B_Port') AND $timeFilter",
     "select": [
      [
       { "params": [ "modulation_type" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Router_A$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Optics0/0/0/29" }
     ]
    }
   ]
  },
  {
   "title": "Frequency ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "THz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"dwdm_carrier_frequency\")\n  |> filter(fn: (r) => r[\"name\"] == \"Optics\"+\"${Router_B_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_B}\")\n  "
    }
   ]
  },
  {
   "title": "wavelength ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "nm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"dwdm_carrier_wavelength\")\n  |> filter(fn: (r) => r[\"name\"] == \"Optics\"+\"${Router_B_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_B}\")\n  "
    }
   ]
  },
  {
   "title": "Pre-FEC/Post-FEC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-controller-otu-oper:otu/controllers/controller/info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"otu_fec_satistics/pre_fec_ber\")\n  |> filter(fn: (r) => r[\"controller_name\"] == \"CoherentDSP\"+\"${Router_B_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_B}\")\n  |> map(fn: (r) => ({r with _value: float(v: r._value)}))\n  "
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-controller-otu-oper:otu/controllers/controller/info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"otu_fec_satistics/post_fec_ber\")\n  |> filter(fn: (r) => r[\"controller_name\"] == \"CoherentDSP\"+\"${Router_B_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_B}\")\n  |> map(fn: (r) => ({r with _value: float(v: r._value)}))\n  "
    }
   ]
  },
  {
   "title": "RX/TX dBm",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-lanes/optics-lane\")\n  |> filter(fn: (r) => r[\"_field\"] == \"receive_power\")\n  |> filter(fn: (r) => r[\"name\"] == \"Optics\"+\"${Router_B_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_B}\")\n  |> map(fn: (r) => ({r with _value: r._value / 100}))\n  "
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-lanes/optics-lane\")\n  |> filter(fn: (r) => r[\"_field\"] == \"transmit_power\")\n  |> filter(fn: (r) => r[\"name\"] == \"Optics\"+\"${Router_B_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_B}\")\n  |> map(fn: (r) => ({r with _value: r._value / 100}))\n  \n  "
    }
   ]
  },
  {
   "title": "Qmargin/Qfactor dB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${otu_pm_path}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"q/average\")\n  |> filter(fn: (r) => r[\"name\"] == \"CoherentDSP\"+\"${Router_B_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_B}\")\n  |> map(fn:(r) => ({ r with _value: float(v: r._value) }))\n  "
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${otu_pm_path}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"qmargin/average\")\n  |> filter(fn: (r) => r[\"name\"] == \"CoherentDSP\"+\"${Router_A_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_A}\")\n  |> map(fn:(r) => ({ r with _value: float(v: r._value) }))\n  "
    }
   ]
  },
  {
   "title": "EC/UC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-pmengine-oper:performance-management/otu/otu-ports/otu-port/otu-current/otu-second30/otu-second30fecs/otu-second30fec",
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${otu_pm_path}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ec_bits/data\" or r[\"_field\"] == \"uc_words/data\")\n  |> filter(fn: (r) => r[\"name\"] == \"CoherentDSP\"+\"${Router_B_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_B}\")",
     "select": [
      [
       { "params": [ "ec_bits/data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Router_A$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "CoherentDSP0/0/0/29" }
     ]
    }
   ]
  },
  {
   "title": "OSNR/ESNR dB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"optical_signal_to_noise_ratio\" or r[\"_field\"] == \"snr\" )\n  |> filter(fn: (r) => r[\"name\"] == \"Optics\"+\"${Router_B_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_B}\")\n  |> map(fn:(r) => ({ r with _value: float(v: r._value) }))\n  "
    }
   ]
  },
  {
   "title": "Temperature ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lane_data/laser_temperature\")\n  |> filter(fn: (r) => r[\"name\"] == \"Optics\"+\"${Router_B_Port}\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Router_B}\")\n  |> map(fn: (r) => ({r with _value: r._value / 100}))\n  "
    }
   ]
  }
 ]
}