version: '3'
services:
  influxdb:
    image: influxdb:2.6.1
    container_name: influxdb
    volumes:
      - influxdbv2:/root/.influxdbv2
    ports:
      - "8086:8086"
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:2.6.1
    container_name: influxdb_cli
    entrypoint: influx setup --bucket telegraf -t secretToken -o cisco --username=admin --password=cisco123 --host=http://influxdb:8086 -f
    restart: on-failure:10
    depends_on:
      - influxdb
  telegraf:
    image: telegraf
    container_name: telegraf
    ports:
    - '8125:8125'
    - '57000:57000'
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb_cli
  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
volumes:
  influxdbv2:
  grafana_data: {}